import Foundation
import AppKit
import CoreGraphics
import UniformTypeIdentifiers

// MARK: - SVG export

enum SVGExporter {

    static func documentSVG(_ doc: PanelDocument) -> String {
        let size = doc.pixelSize
        var s = """
        <?xml version="1.0" encoding="UTF-8"?>
        <!-- Generated by PanelGenerator — "\(doc.name)", \(doc.widthHP)HP \(doc.format.rawValue) -->
        \(svgOpenTag(width: size.width, height: size.height, units: doc.svgUnits))
        <rect x="0" y="0" width="\(Geo.fmt(size.width))" height="\(Geo.fmt(size.height))" fill="\(doc.background.hexString)"/>

        """
        // Components are drawn by Rack / MetaModule on top of the panel.
        // Painting them into the artwork too would show them through from
        // underneath, so only decoration reaches the exported SVG.
        // Widget artwork belongs to its widget's own SVG, not to the panel —
        // Rack composites the widget on top, so drawing it here too would show
        // it through from underneath.
        for el in doc.elements
        where el.isHidden != true && el.isTemplate != true
            && !el.role.isComponent && !doc.isWidgetArtwork(el) {
            s += elementSVG(el, textAsPaths: doc.textAsPaths)
            s += "\n"
        }
        s += "</svg>\n"
        return s
    }

    /// `width`/`height` in the document's chosen unit, with the viewBox left in
    /// panel pixels so no geometry is rescaled.
    ///
    /// Millimetres matter downstream: helper.py takes the `mm` branch and skips
    /// its 75-dpi guess, and MetaModule rasterisers read the physical size from
    /// this attribute — one in this very toolchain raises if it is not in mm.
    /// Width converts exactly (15 px/HP × 25.4/75 = 5.08 mm); height comes out
    /// 128.69 mm against the spec's 128.5, because Rack's own RACK_GRID_HEIGHT
    /// is 380 px. Rack forces the module box height anyway, and both round to
    /// the same 240 px MetaModule faceplate.
    static func svgOpenTag(width: CGFloat, height: CGFloat, units: SVGUnits) -> String {
        let w: String, h: String
        switch units {
        case .pixels:
            w = Geo.fmt(width)
            h = Geo.fmt(height)
        case .millimetres:
            w = Geo.fmt(PanelMetrics.mm(width)) + "mm"
            h = Geo.fmt(PanelMetrics.mm(height)) + "mm"
        }
        return "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"\(w)\" height=\"\(h)\""
            + " viewBox=\"0 0 \(Geo.fmt(width)) \(Geo.fmt(height))\">"
    }

    /// Path elements for a set of parts, without the enclosing group.
    static func partsBody(_ parts: [ShapePart]) -> String {
        var body = ""
        for part in parts {
            let d = PathSVG.d(part.path)
            guard !d.isEmpty else { continue }
            body += "<path d=\"\(d)\"\(paintAttrs(fill: part.fill, stroke: part.stroke, width: part.lineWidth))/>"
        }
        return body
    }

    static func paintAttrs(fill: ColorSpec?, stroke: ColorSpec?, width: CGFloat) -> String {
        var a = ""
        if let f = fill {
            a += " fill=\"\(f.hexString)\""
            if f.a < 1 { a += String(format: " fill-opacity=\"%.2f\"", f.a) }
        } else {
            a += " fill=\"none\""
        }
        if let st = stroke {
            a += " stroke=\"\(st.hexString)\" stroke-width=\"\(Geo.fmt(max(width, 0.1)))\""
            if st.a < 1 { a += String(format: " stroke-opacity=\"%.2f\"", st.a) }
        }
        return a
    }

    static func elementSVG(_ el: PanelElement, textAsPaths: Bool = true) -> String {
        let c = el.center

        // Live <text> is only for handing a panel to a vector editor. VCV Rack
        // parses SVG with nanosvg, which has no text support at all: these
        // elements are dropped without warning, labels and all. Outlines (the
        // default, handled by the generic parts path below) are what Rack and
        // the MetaModule asset pipeline can actually render.
        if el.kind == .text && !textAsPaths {
            let weight = el.params.bold ? "600" : "400"
            let baselineY = Geo.fmt(c.y + el.params.fontSize * 0.35)
            let esc = el.params.text
                .replacingOccurrences(of: "&", with: "&amp;")
                .replacingOccurrences(of: "<", with: "&lt;")
                .replacingOccurrences(of: ">", with: "&gt;")
            var t = "<text x=\"\(Geo.fmt(c.x))\" y=\"\(baselineY)\" text-anchor=\"middle\" "
            t += "font-family=\"-apple-system, 'Helvetica Neue', Helvetica, Arial, sans-serif\" "
            t += "font-size=\"\(Geo.fmt(el.params.fontSize))\" font-weight=\"\(weight)\" "
            t += "fill=\"\(el.fill.hexString)\"\(el.rotation != 0 ? "" : "")>\(esc)</text>"
            if el.rotation != 0 {
                return "<g transform=\"rotate(\(Geo.fmt(el.rotation)) \(Geo.fmt(c.x)) \(Geo.fmt(c.y)))\">\(t)</g>"
            }
            return t
        }

        var body = ""
        for part in Renderer.parts(for: el) {
            let dstr = PathSVG.d(part.path)
            guard !dstr.isEmpty else { continue }
            body += "<path d=\"\(dstr)\"\(paintAttrs(fill: part.fill, stroke: part.stroke, width: part.lineWidth))/>"
        }
        guard !body.isEmpty else { return "" }

        var transform = ""
        if el.rotation != 0 {
            transform = " transform=\"rotate(\(Geo.fmt(el.rotation)) \(Geo.fmt(c.x)) \(Geo.fmt(c.y)))\""
        }
        return "<g\(transform)>\(body)</g>"
    }

    /// A standalone SVG holding nothing but the `components` layer, in the
    /// shape Rack's `helper.py createmodule` expects: one shape per component,
    /// classified by fill colour, named through `data-name`, with an optional
    /// `#WidgetClass` suffix. Circles rather than rects, so helper.py emits the
    /// `…Centered` constructors — positioning by centre is what you want.
    ///
    /// Kept out of the panel file deliberately: everything in the panel SVG is
    /// artwork as far as Rack is concerned, and hiding a marker layer behind
    /// `display="none"` is a gamble on the SVG parser's attribute support.
    static func componentsSVG(_ doc: PanelDocument) -> String {
        let size = doc.pixelSize
        var s = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        s += "<!-- PanelGenerator components layer for \"\(escape(doc.name))\".\n"
        s += "     helper.py createmodule \(doc.moduleSlug) <this file> <YourModule.cpp>\n"
        s += "     Positions only; the panel artwork is in the companion SVG. -->\n"
        s += svgOpenTag(width: size.width, height: size.height, units: doc.svgUnits) + "\n"
        s += "<g id=\"components\">\n"

        let ids = CodeGen.identifiers(doc)   // same disambiguation as the enums
        for el in doc.components {
            guard let fill = el.role.helperFill else { continue }
            let c = el.center
            let r = max(min(el.w, el.h) / 2, 1)
            // helper.py pastes this class name straight into the generated
            // source, so it has to be the name as C++ will see it. Without the
            // namespace the direct emission says lcarsui::LcarsKnob and the
            // helper.py route says LcarsKnob, and only one of them compiles.
            var widgetClass = el.widgetClass
            if el.widgetSource == .custom, !widgetClass.isEmpty {
                widgetClass = CodeGen.namespacePrefix(doc) + widgetClass
            }
            var dataName = ids[el.id] ?? el.identifierStem
            if !widgetClass.isEmpty { dataName += "#" + widgetClass }
            s += "<circle cx=\"\(Geo.fmt(c.x))\" cy=\"\(Geo.fmt(c.y))\" r=\"\(Geo.fmt(r))\""
            s += " fill=\"\(fill)\" data-name=\"\(escape(dataName))\"/>\n"
        }

        s += "</g>\n</svg>\n"
        return s
    }

    /// Which slice of a component's artwork a file holds.
    enum ComponentLayer {
        case whole
        /// A knob's static body — Rack's `bg` SvgWidget, below the transform.
        case knobBackground
        /// The part Rack rotates.
        case knobForeground
        /// One position of a switch or button. Rack's SvgSwitch holds a frame
        /// per position and picks between them by parameter value, so the
        /// artwork is exported once per position with the toggle moved.
        case switchFrame(index: Int, of: Int)
    }

    /// One component's artwork as a standalone SVG, sized to the element with
    /// its origin at (0,0). This is what a custom widget's `setSvg()` loads —
    /// and since Rack takes the widget's box size from the file, the element's
    /// size here *is* the control's size in Rack.
    /// A composed widget's artwork: every member of the group, moved so the
    /// widget's own bounds start at the origin, split by which parts turn.
    static func componentSVG(_ anchor: PanelElement,
                             in doc: PanelDocument,
                             layer: ComponentLayer = .whole,
                             units: SVGUnits = .millimetres) -> String {
        let members = doc.widgetMembers(of: anchor)
        guard members.count > 1 else {
            return componentSVG(anchor, layer: layer, units: units)
        }
        let bounds = doc.widgetBounds(of: anchor)

        var parts: [ShapePart] = []
        for member in members where member.isHidden != true {
            switch layer {
            case .knobBackground where member.rotatesWithValue: continue
            case .knobForeground where !member.rotatesWithValue: continue
            default: break
            }
            var local = member
            local.x -= bounds.minX
            local.y -= bounds.minY
            if member.kind.isKnob { local.params.pointerAngle = 0 }
            // Only the anchor knows which position it is in; the rest of the
            // group is the housing and is the same in every frame.
            if case .switchFrame(let index, let count) = layer, member.id == anchor.id {
                local.params.value = count > 1 ? CGFloat(index) / CGFloat(count - 1) : 0
            }
            // Rotation is a transform on the panel and a CTM on the canvas, so
            // it lives outside the parts — which meant a rotated piece of a
            // composed widget exported straight, silently. Bake it in here:
            // the widget's own SVG has no outer transform to carry it.
            var made = Renderer.parts(for: local)
            if local.rotation != 0 {
                let c = local.center
                var t = CGAffineTransform(translationX: c.x, y: c.y)
                    .rotated(by: Geo.deg2rad(local.rotation))
                    .translatedBy(x: -c.x, y: -c.y)
                made = made.compactMap { part in
                    guard let turned = part.path.copy(using: &t) else { return nil }
                    var out = part
                    out.path = turned
                    return out
                }
            }
            parts += made
        }

        let title = anchor.customWidgetName.isEmpty ? anchor.identifierStem : anchor.customWidgetName
        var s = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        s += "<!-- PanelGenerator widget \"\(escape(title))\", \(members.count) parts -->\n"
        s += svgOpenTag(width: max(bounds.width, 1), height: max(bounds.height, 1), units: units) + "\n"
        s += partsBody(parts)
        s += "\n</svg>\n"
        return s
    }

    static func componentSVG(_ el: PanelElement,
                             layer: ComponentLayer = .whole,
                             units: SVGUnits = .millimetres) -> String {
        var local = el
        local.x = 0
        local.y = 0
        local.rotation = 0
        // Knob artwork is drawn pointing straight up: Rack sweeps it from
        // minAngle to maxAngle itself, so the editor's pointer angle baked into
        // the file would become a permanent offset on every instance.
        if el.kind.isKnob { local.params.pointerAngle = 0 }
        if case .switchFrame(let index, let count) = layer {
            local.params.value = count > 1 ? CGFloat(index) / CGFloat(count - 1) : 0
        }

        let all = Renderer.parts(for: local)
        let parts: [ShapePart]
        switch layer {
        case .whole, .switchFrame: parts = all
        case .knobBackground:      parts = Renderer.knobLayers(all)?.bg ?? all
        case .knobForeground:      parts = Renderer.knobLayers(all)?.fg ?? []
        }

        let w = max(el.w, 1), h = max(el.h, 1)
        let title = el.customWidgetName.isEmpty ? el.identifierStem : el.customWidgetName
        var s = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        s += "<!-- PanelGenerator component \"\(escape(title))\" -->\n"
        s += svgOpenTag(width: w, height: h, units: units) + "\n"
        s += partsBody(parts)
        s += "\n</svg>\n"
        return s
    }

    static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "&", with: "&amp;")
         .replacingOccurrences(of: "<", with: "&lt;")
         .replacingOccurrences(of: ">", with: "&gt;")
         .replacingOccurrences(of: "\"", with: "&quot;")
    }
}

// MARK: - PNG export

enum PNGExporter {

    struct PNGError: LocalizedError {
        let message: String
        var errorDescription: String? { message }
    }

    /// Rasterises the panel at `scale`× panel pixels (4× ≈ print quality).
    static func pngData(_ doc: PanelDocument, scale: CGFloat = 4) throws -> Data {
        let size = doc.pixelSize
        let pw = Int((size.width * scale).rounded())
        let ph = Int((size.height * scale).rounded())
        guard pw > 0, ph > 0 else {
            throw PNGError(message: "Panel size is degenerate.")
        }

        guard let rep = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: pw,
            pixelsHigh: ph,
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0)
        else {
            throw PNGError(message: "Could not allocate bitmap context.")
        }
        rep.size = NSSize(width: size.width, height: size.height)

        guard let buf = rep.bitmapData else {
            throw PNGError(message: "Bitmap buffer unavailable.")
        }
        let cg = CGContext(
            data: buf,
            width: pw,
            height: ph,
            bitsPerComponent: 8,
            bytesPerRow: rep.bytesPerRow,
            space: CGColorSpace(name: CGColorSpace.sRGB) ?? CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)
        guard let cg else {
            throw PNGError(message: "Could not create CGContext over bitmap buffer.")
        }

        // y-down, panel-point units — matches the canvas view and SVG space.
        cg.translateBy(x: 0, y: CGFloat(ph))
        cg.scaleBy(x: scale, y: -scale)

        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(cgContext: cg, flipped: true)
        Renderer.drawBackground(doc, in: cg)
        // The PNG is what the panel looks like, so the template a panel was
        // traced from has no business in it.
        for el in doc.elements where el.isHidden != true && el.isTemplate != true {
            Renderer.draw(el, in: cg)
        }
        NSGraphicsContext.restoreGraphicsState()

        guard let data = rep.representation(using: .png, properties: [:]) else {
            throw PNGError(message: "PNG encoding failed.")
        }
        return data
    }

    static var suggestedType: UTType { .png }
}
